services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: . 
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/notes-db
      - JWT_SECRET=um_segredo_muito_longo_e_dificil_de_adivinhar_123!
    depends_on:
      - mongodb

  frontend:
    build: ./client 
    ports:
      - "5173:5173"
    stdin_open: true 
    tty: true
    depends_on:
      - backend
    command: npm run dev -- --host 

volumes:
  mongo-data: